enum ProductCategories {
    ALL_CATEGORIES="ALL_CATEGORIES",
    APPAREL="APPAREL",
    APPLIANCES="APPLIANCES",
    BABY="BABY",
    BEAUTY="BEAUTY",
    COMPUTERS="COMPUTERS",
    ELECTRONICS="ELECTRONICS",
}

export default ProductCategories